### ISSUE TITLE
Add support for evaluating expressions in the debugger

### ISSUE THREAD

**Issue by alins** [ccw-ide/ccw#751]
i can debug clojure code just fine, the debugger stops at breakpoints and i can see the variables. now i would like to execute add hoc code to see what's going on and it doesn't look like is working. If i type code in REPL i get "CompilerException java.lang.RuntimeException: Unable to resolve symbol: <symbol> in this context, compiling:(NO_SOURCE_PATH:1:1)". the REPL seem to be disconnected from the debug session so it doesn't have any clue about the context. using eclipse built-in "Expressions" doesn't work either.

I don't know if is this is possible, but i would be awesome if the REPL will have the proper context so ad-hoc code can be executed while the execution is halted on the breakpoint.

**Comment by laurentpetit** [comment]
This could be very interesting indeed. I haven't investigated this area much, meaning I will need to first learn about how things work. Hopefully there's a lot of stuff available, so it's more a matter of finding time than a matter of feasibility, I think.
